String cssStyle = 
"body {"
"  font-family: Arial;"
"  margin: 0;"
"}"
".header {"
"  padding: 10px;"
"  text-align: center;"
"  background: #339cff;"
"  color: white;"
"  font-size: 30px;"
"  text-shadow: 2px 2px black;"
"} "
" "
".content {padding:20px; text-align: center;}"
" "
".button {"
"  background-color: #339cff;"
"  text-align: center;"
"  text-decoration: none;"
"  transition-duration: 0.4s;"
"  color: white;"
"  border-radius: 4px;"
"  padding: 10px 24px;"
"  text-transform: uppercase;"
"  font-weight: bold;"
"  text-shadow: 1px 1px black;"
"} "
" "
".button:hover {"
"  background-color: #80c1ff;"
"}";


String jsFunctions =
"var refreshData = setInterval(fetchData, 2000);"
""
"function fetchData() {"
"  var request = new XMLHttpRequest();"
"  request.open('GET', window.location.hostname + '/api');"
"  request.onload = function() {"
"    var data = JSON.parse(request.responseText);"
"    document.getElementById('curTemps').innerHTML = data.current_temp_c + '°C / ' + data.current_temp_c + '°F' ;"
"    document.getElementById('curHum').innerHTML = data.current_humidity + '%';"
"    console.log(data.current_temp_c);"
"  }"
"}";
